export const DEFAULT_ROLE_KEYS = [
  'HOTEL_OWNER',
  'HOTEL_ADMIN',
  'GENERAL_MANAGER',
  'FRONT_DESK_CASHIER',
  'HOUSEKEEPING_SUPERVISOR',
  'HOUSEKEEPING_ATTENDANT',
  'MAINTENANCE_SUPERVISOR',
  'MAINTENANCE_TECHNICIAN',
  'ACCOUNTANT',
  'RESTAURANT_CASHIER',
  'WAITER',
  'STOREKEEPER',
  'PROCUREMENT_OFFICER',
  'HR_ADMIN',
  'GUEST',
] as const;

export type DefaultRoleKey = (typeof DEFAULT_ROLE_KEYS)[number];

export type DefaultRole = {
  key: DefaultRoleKey;
  name: string;
  description: string;
  permissions: readonly string[];
};

export const DEFAULT_ROLES = [
  {
    key: 'HOTEL_OWNER',
    name: 'Hotel Owner',
    description: 'Executive visibility, approvals, and audit oversight.',
    permissions: [
      'reports.dashboard.read',
      'reports.daily_summary.read',
      'reports.occupancy.read',
      'reports.arrivals_departures.read',
      'reports.room_status.read',
      'reports.revenue.read',
      'reports.payment_summary.read',
      'reports.department_performance.read',
      'reports.profit_summary.read',
      'reports.housekeeping.read',
      'reports.maintenance.read',
      'reports.outlet_sales.read',
      'reports.inventory.read',
      'reports.procurement.read',
      'approval_requests.read',
      'approval_requests.approve',
      'approval_requests.reject',
      'large_discount.approve',
      'refund.approve',
      'purchase_order.approve',
      'audit_logs.read',
      'audit_logs.export',
      'hotel.profile.read',
      'floors.read',
      'room_types.read',
      'room_amenities.read',
      'rooms.read',
      'rooms.status.read',
      'rooms.availability.read',
      'users.read',
      'roles.read',
      'permissions.read',
      'employees.read',
      'departments.read',
      'notifications.read',
    ],
  },
  {
    key: 'HOTEL_ADMIN',
    name: 'Hotel Admin',
    description:
      'Configure the hotel system and manage users, roles, rooms, departments, and settings.',
    permissions: [
      'hotel.profile.read',
      'hotel.profile.update',
      'hotel.settings.read',
      'hotel.settings.update',
      'payment_methods.create',
      'payment_methods.read',
      'payment_methods.update',
      'payment_methods.delete',
      'outlets.create',
      'outlets.read',
      'outlets.update',
      'outlets.delete',
      'departments.create',
      'departments.read',
      'departments.update',
      'departments.delete',
      'users.create',
      'users.read',
      'users.update',
      'users.deactivate',
      'users.activate',
      'users.reset_password',
      'users.assign_role',
      'roles.create',
      'roles.read',
      'roles.update',
      'roles.delete',
      'roles.assign',
      'permissions.read',
      'permissions.assign',
      'floors.create',
      'floors.read',
      'floors.update',
      'floors.delete',
      'room_types.create',
      'room_types.read',
      'room_types.update',
      'room_types.delete',
      'rooms.create',
      'rooms.read',
      'rooms.update',
      'rooms.delete',
      'rooms.status.read',
      'rooms.status.update',
      'rooms.out_of_order.mark',
      'rooms.out_of_order.clear',
      'rooms.availability.read',
      'room_amenities.create',
      'room_amenities.read',
      'room_amenities.update',
      'room_amenities.delete',
      'audit_logs.read',
      'reports.dashboard.read',
      'reports.daily_summary.read',
      'employees.read',
      'notifications.read',
      'files.upload',
      'files.read',
      'files.delete',
    ],
  },
  {
    key: 'GENERAL_MANAGER',
    name: 'General Manager',
    description:
      'Run daily operations, coordinate departments, review reports, and approve sensitive operational actions.',
    permissions: [
      'reports.dashboard.read',
      'reports.daily_summary.read',
      'reports.occupancy.read',
      'reports.arrivals_departures.read',
      'reports.room_status.read',
      'reports.revenue.read',
      'reports.housekeeping.read',
      'reports.maintenance.read',
      'reports.outlet_sales.read',
      'availability.read',
      'booking_calendar.read',
      'arrivals.read',
      'departures.read',
      'in_house_guests.read',
      'guests.read',
      'guests.history.read',
      'guest_requests.read',
      'guest_requests.update',
      'guest_requests.close',
      'reservations.read',
      'floors.read',
      'room_types.read',
      'room_amenities.read',
      'rooms.read',
      'rooms.status.read',
      'rooms.status.update',
      'rooms.out_of_order.mark',
      'rooms.out_of_order.clear',
      'rooms.availability.read',
      'housekeeping.dashboard.read',
      'housekeeping.tasks.read',
      'housekeeping.tasks.assign',
      'housekeeping.assignees.read',
      'housekeeping.tasks.reassign',
      'housekeeping.tasks.inspect',
      'housekeeping.tasks.approve',
      'housekeeping.productivity.read',
      'maintenance.dashboard.read',
      'maintenance.tickets.create',
      'maintenance.tickets.read',
      'maintenance.tickets.assign',
      'maintenance.tickets.update',
      'maintenance.tickets.approve',
      'preventive_maintenance.read',
      'assets.read',
      'folios.read',
      'folios.discount.approve',
      'folios.adjustment.approve',
      'payments.read',
      'payments.refund.review',
      'payments.refund.approve',
      'approval_requests.read',
      'approval_requests.approve',
      'approval_requests.reject',
      'large_discount.approve',
      'refund.approve',
      'purchase_request.approve',
      'room_out_of_order.approve',
      'audit_logs.read',
      'notifications.read',
      'employees.read',
      'departments.read',
      'hotel.profile.read',
      'hotel.settings.read',
    ],
  },
  {
    key: 'FRONT_DESK_CASHIER',
    name: 'Front Desk Cashier',
    description:
      'Manage bookings, check-in, stay flow, checkout, folios, payments, and receipts.',
    permissions: [
      'availability.read',
      'booking_calendar.read',
      'arrivals.read',
      'departures.read',
      'in_house_guests.read',
      'guests.create',
      'guests.read',
      'guests.update',
      'guests.notes.create',
      'guests.notes.read',
      'guests.preferences.read',
      'guests.preferences.update',
      'reservations.create',
      'reservations.read',
      'reservations.update',
      'reservations.cancel',
      'reservations.confirm',
      'reservations.deposit.record',
      'check_in.execute',
      'check_out.execute',
      'room_assignment.create',
      'room_assignment.update',
      'room_move.execute',
      'stay_extension.execute',
      'floors.read',
      'room_types.read',
      'rooms.read',
      'rooms.status.read',
      'rooms.availability.read',
      'guest_requests.create',
      'guest_requests.read',
      'guest_requests.update',
      'guest_requests.close',
      'folios.create',
      'folios.read',
      'folios.update',
      'folios.close',
      'folios.manual_charge.create',
      'folios.discount.apply.small',
      'folios.discount.request',
      'invoices.generate',
      'invoices.read',
      'receipts.generate',
      'receipts.read',
      'payments.record',
      'payments.read',
      'payments.refund.request',
      'maintenance.tickets.create',
      'housekeeping.issues.report',
      'notifications.read',
      'files.upload',
      'files.read',
    ],
  },
  {
    key: 'HOUSEKEEPING_SUPERVISOR',
    name: 'Housekeeping Supervisor',
    description:
      'Assign cleaning tasks, monitor readiness, inspect rooms, and coordinate with front desk.',
    permissions: [
      'housekeeping.dashboard.read',
      'housekeeping.tasks.create',
      'housekeeping.tasks.read',
      'housekeeping.tasks.assign',
      'housekeeping.assignees.read',
      'housekeeping.tasks.reassign',
      'housekeeping.tasks.inspect',
      'housekeeping.tasks.approve',
      'housekeeping.issues.report',
      'housekeeping.issues.read',
      'housekeeping.productivity.read',
      'room_cleaning_status.update',
      'floors.read',
      'room_types.read',
      'rooms.read',
      'rooms.status.read',
      'rooms.status.update',
      'maintenance.tickets.create',
      'files.upload',
      'files.read',
      'notifications.read',
    ],
  },
  {
    key: 'HOUSEKEEPING_ATTENDANT',
    name: 'Housekeeping Attendant',
    description: 'View and complete assigned room cleaning tasks.',
    permissions: [
      'housekeeping.tasks.read.assigned',
      'housekeeping.tasks.start.assigned',
      'housekeeping.tasks.complete.assigned',
      'housekeeping.issues.report',
      'room_cleaning_status.update.assigned',
      'maintenance.tickets.create',
      'files.upload',
      'files.read',
      'notifications.read',
    ],
  },
  {
    key: 'MAINTENANCE_SUPERVISOR',
    name: 'Maintenance Supervisor',
    description:
      'Control maintenance workload, assign tickets, manage room out-of-order status, and approve completion.',
    permissions: [
      'maintenance.dashboard.read',
      'maintenance.tickets.create',
      'maintenance.tickets.read',
      'maintenance.tickets.assign',
      'maintenance.tickets.update',
      'maintenance.tickets.approve',
      'rooms.read',
      'rooms.status.read',
      'rooms.status.update',
      'rooms.out_of_order.mark',
      'rooms.out_of_order.clear',
      'rooms.availability.read',
      'preventive_maintenance.create',
      'preventive_maintenance.read',
      'preventive_maintenance.update',
      'preventive_maintenance.delete',
      'assets.create',
      'assets.read',
      'assets.update',
      'assets.delete',
      'reports.maintenance.read',
      'files.upload',
      'files.read',
      'notifications.read',
    ],
  },
  {
    key: 'MAINTENANCE_TECHNICIAN',
    name: 'Maintenance Technician',
    description: 'Work on assigned maintenance tickets.',
    permissions: [
      'maintenance.tickets.read.assigned',
      'maintenance.tickets.start.assigned',
      'maintenance.tickets.update.assigned',
      'maintenance.tickets.complete.assigned',
      'maintenance.parts.request',
      'maintenance.photos.upload',
      'files.upload',
      'files.read',
      'notifications.read',
    ],
  },
  {
    key: 'ACCOUNTANT',
    name: 'Accountant',
    description: 'Review, reconcile, and report financial activity.',
    permissions: [
      'finance.dashboard.read',
      'transactions.read',
      'transactions.reconcile',
      'payments.read',
      'payments.refund.review',
      'payments.refund.approve',
      'payments.reconcile',
      'invoices.read',
      'receipts.read',
      'accounts_receivable.read',
      'accounts_receivable.update',
      'daily_close.create',
      'daily_close.read',
      'tax_reports.read',
      'service_charge_reports.read',
      'reports.revenue.read',
      'reports.payment_summary.read',
      'reports.outlet_sales.read',
      'outlet_sales.read',
      'folios.read',
      'adjustments.read',
      'adjustments.approve',
      'audit_logs.read',
    ],
  },
  {
    key: 'RESTAURANT_CASHIER',
    name: 'Restaurant Cashier',
    description:
      'Enter POS orders, prepare receipts, accept payment, and charge orders to rooms.',
    permissions: [
      'pos.dashboard.read',
      'pos.orders.create',
      'pos.orders.read',
      'pos.orders.update',
      'pos.orders.close',
      'pos.orders.cancel',
      'pos.payments.record',
      'pos.receipts.generate',
      'pos.charge_to_room',
      'pos.menu_items.read',
      'outlet_sales.read.own_outlet',
      'folios.read',
      'folios.manual_charge.create',
      'notifications.read',
    ],
  },
  {
    key: 'WAITER',
    name: 'Waiter',
    description:
      'Traditional order taking and delivery; seeded for future mobile or tablet order flow.',
    permissions: [
      'waiter.orders.create',
      'waiter.orders.read.assigned',
      'waiter.orders.delivery.update',
      'room_service.requests.read.assigned',
      'room_service.delivery.update',
      'notifications.read',
    ],
  },
  {
    key: 'STOREKEEPER',
    name: 'Storekeeper',
    description:
      'Manage stock receiving, issuing, transfers, and reorder alerts.',
    permissions: [
      'inventory.items.create',
      'inventory.items.read',
      'inventory.items.update',
      'inventory.stock.receive',
      'inventory.stock.issue',
      'inventory.stock.transfer',
      'inventory.stock.adjust.request',
      'inventory.reorder_alerts.read',
      'inventory.movements.read',
      'inventory.counts.create',
      'inventory.counts.read',
      'purchase_requests.create',
      'purchase_requests.read',
      'suppliers.read',
      'files.upload',
      'files.read',
      'notifications.read',
    ],
  },
  {
    key: 'PROCUREMENT_OFFICER',
    name: 'Procurement Officer',
    description:
      'Manage purchase requests, purchase orders, suppliers, and goods received.',
    permissions: [
      'purchase_requests.create',
      'purchase_requests.read',
      'purchase_requests.update',
      'purchase_orders.create',
      'purchase_orders.read',
      'purchase_orders.update',
      'goods_received.create',
      'goods_received.read',
      'suppliers.create',
      'suppliers.read',
      'suppliers.update',
      'inventory.reorder_alerts.read',
      'inventory.items.read',
      'notifications.read',
      'files.upload',
      'files.read',
    ],
  },
  {
    key: 'HR_ADMIN',
    name: 'HR Admin',
    description:
      'Manage employee records, departments, positions, shifts, attendance, leave, and staff documents.',
    permissions: [
      'employees.create',
      'employees.read',
      'employees.update',
      'employees.deactivate',
      'employees.activate',
      'departments.read',
      'job_positions.create',
      'job_positions.read',
      'job_positions.update',
      'job_positions.delete',
      'shifts.create',
      'shifts.read',
      'shifts.update',
      'shifts.delete',
      'attendance.create',
      'attendance.read',
      'attendance.update',
      'leave_requests.create',
      'leave_requests.read',
      'leave_requests.approve',
      'leave_requests.reject',
      'staff_documents.upload',
      'staff_documents.read',
      'staff_documents.delete',
      'files.upload',
      'files.read',
      'notifications.read',
    ],
  },
  {
    key: 'GUEST',
    name: 'Guest',
    description:
      'Guest portal access to own reservations, payments, invoices, receipts, and service requests.',
    permissions: [
      'guest_portal.booking.create',
      'guest_portal.reservations.read.own',
      'guest_portal.profile.update.own',
      'guest_portal.payments.create.own',
      'guest_portal.invoices.read.own',
      'guest_portal.receipts.read.own',
      'guest_portal.service_requests.create.own',
      'guest_portal.service_requests.read.own',
      'guest_portal.feedback.create.own',
      'files.upload',
      'files.read.own',
    ],
  },
] as const satisfies readonly DefaultRole[];
