export type DefaultPermission = {
  key: string;
  name: string;
  category: string;
};

export type DefaultPermissionCategory = {
  category: string;
  keys: readonly string[];
};

export const DEFAULT_PERMISSION_CATEGORIES = [
  {
    category: 'hotel_settings',
    keys: [
      'hotel.profile.read',
      'hotel.profile.update',
      'hotel.settings.read',
      'hotel.settings.update',
      'payment_methods.create',
      'payment_methods.read',
      'payment_methods.update',
      'payment_methods.delete',
      'outlets.create',
      'outlets.read',
      'outlets.update',
      'outlets.delete',
      'departments.create',
      'departments.read',
      'departments.update',
      'departments.delete',
    ],
  },
  {
    category: 'users_roles',
    keys: [
      'users.create',
      'users.read',
      'users.update',
      'users.deactivate',
      'users.activate',
      'users.reset_password',
      'users.assign_role',
      'roles.create',
      'roles.read',
      'roles.update',
      'roles.delete',
      'roles.assign',
      'permissions.read',
      'permissions.assign',
    ],
  },
  {
    category: 'rooms',
    keys: [
      'floors.create',
      'floors.read',
      'floors.update',
      'floors.delete',
      'room_types.create',
      'room_types.read',
      'room_types.update',
      'room_types.delete',
      'rooms.create',
      'rooms.read',
      'rooms.update',
      'rooms.delete',
      'rooms.status.read',
      'rooms.status.update',
      'rooms.out_of_order.mark',
      'rooms.out_of_order.clear',
      'rooms.availability.read',
      'room_amenities.create',
      'room_amenities.read',
      'room_amenities.update',
      'room_amenities.delete',
    ],
  },
  {
    category: 'guest_management',
    keys: [
      'guests.create',
      'guests.read',
      'guests.update',
      'guests.delete',
      'guests.notes.create',
      'guests.notes.read',
      'guests.notes.update',
      'guests.history.read',
      'guests.preferences.read',
      'guests.preferences.update',
    ],
  },
  {
    category: 'reservations_front_desk',
    keys: [
      'availability.read',
      'booking_calendar.read',
      'reservations.create',
      'reservations.read',
      'reservations.update',
      'reservations.cancel',
      'reservations.no_show.mark',
      'reservations.confirm',
      'reservations.deposit.record',
      'check_in.execute',
      'check_out.execute',
      'room_assignment.create',
      'room_assignment.update',
      'room_move.execute',
      'stay_extension.execute',
      'in_house_guests.read',
      'arrivals.read',
      'departures.read',
      'guest_requests.create',
      'guest_requests.read',
      'guest_requests.update',
      'guest_requests.close',
    ],
  },
  {
    category: 'folios_billing',
    keys: [
      'folios.create',
      'folios.read',
      'folios.update',
      'folios.close',
      'folios.manual_charge.create',
      'folios.charge.void',
      'folios.discount.apply.small',
      'folios.discount.request',
      'folios.discount.approve',
      'folios.adjustment.request',
      'folios.adjustment.approve',
      'invoices.generate',
      'invoices.read',
      'receipts.generate',
      'receipts.read',
    ],
  },
  {
    category: 'payments',
    keys: [
      'payments.record',
      'payments.read',
      'payments.update',
      'payments.void',
      'payments.refund.request',
      'payments.refund.review',
      'payments.refund.approve',
      'payments.reconcile',
      'payments.methods.read',
      'finance.dashboard.read',
      'transactions.read',
      'transactions.reconcile',
      'accounts_receivable.read',
      'accounts_receivable.update',
      'daily_close.create',
      'daily_close.read',
      'tax_reports.read',
      'service_charge_reports.read',
      'adjustments.read',
      'adjustments.approve',
    ],
  },
  {
    category: 'housekeeping',
    keys: [
      'housekeeping.dashboard.read',
      'housekeeping.tasks.create',
      'housekeeping.tasks.read',
      'housekeeping.tasks.read.assigned',
      'housekeeping.tasks.assign',
      'housekeeping.assignees.read',
      'housekeeping.tasks.reassign',
      'housekeeping.tasks.start',
      'housekeeping.tasks.start.assigned',
      'housekeeping.tasks.complete',
      'housekeeping.tasks.complete.assigned',
      'housekeeping.tasks.inspect',
      'housekeeping.tasks.approve',
      'housekeeping.issues.report',
      'housekeeping.issues.read',
      'housekeeping.productivity.read',
      'room_cleaning_status.update',
      'room_cleaning_status.update.assigned',
    ],
  },
  {
    category: 'maintenance',
    keys: [
      'maintenance.dashboard.read',
      'maintenance.tickets.create',
      'maintenance.tickets.read',
      'maintenance.tickets.read.assigned',
      'maintenance.tickets.assign',
      'maintenance.tickets.start',
      'maintenance.tickets.start.assigned',
      'maintenance.tickets.update',
      'maintenance.tickets.update.assigned',
      'maintenance.tickets.complete',
      'maintenance.tickets.complete.assigned',
      'maintenance.tickets.approve',
      'maintenance.parts.request',
      'maintenance.photos.upload',
      'preventive_maintenance.create',
      'preventive_maintenance.read',
      'preventive_maintenance.update',
      'preventive_maintenance.delete',
      'assets.create',
      'assets.read',
      'assets.update',
      'assets.delete',
    ],
  },
  {
    category: 'pos_outlets',
    keys: [
      'pos.dashboard.read',
      'pos.orders.create',
      'pos.orders.read',
      'pos.orders.update',
      'pos.orders.close',
      'pos.orders.cancel',
      'pos.payments.record',
      'pos.receipts.generate',
      'pos.charge_to_room',
      'pos.menu_items.create',
      'pos.menu_items.read',
      'pos.menu_items.update',
      'pos.menu_items.delete',
      'outlet_sales.read',
      'outlet_sales.read.own_outlet',
      'room_service.requests.create',
      'room_service.requests.read',
      'room_service.requests.read.assigned',
      'room_service.requests.update',
      'room_service.delivery.update',
      'waiter.orders.create',
      'waiter.orders.read.assigned',
      'waiter.orders.delivery.update',
    ],
  },
  {
    category: 'inventory',
    keys: [
      'inventory.items.create',
      'inventory.items.read',
      'inventory.items.update',
      'inventory.items.delete',
      'inventory.stock.receive',
      'inventory.stock.issue',
      'inventory.stock.transfer',
      'inventory.stock.adjust',
      'inventory.stock.adjust.request',
      'inventory.stock.adjust.approve',
      'inventory.reorder_alerts.read',
      'inventory.movements.read',
      'inventory.counts.create',
      'inventory.counts.read',
      'inventory.counts.approve',
    ],
  },
  {
    category: 'procurement',
    keys: [
      'purchase_requests.create',
      'purchase_requests.read',
      'purchase_requests.update',
      'purchase_requests.approve',
      'purchase_requests.reject',
      'purchase_orders.create',
      'purchase_orders.read',
      'purchase_orders.update',
      'purchase_orders.approve',
      'purchase_orders.cancel',
      'goods_received.create',
      'goods_received.read',
      'suppliers.create',
      'suppliers.read',
      'suppliers.update',
      'suppliers.delete',
    ],
  },
  {
    category: 'hr',
    keys: [
      'employees.create',
      'employees.read',
      'employees.update',
      'employees.deactivate',
      'employees.activate',
      'job_positions.create',
      'job_positions.read',
      'job_positions.update',
      'job_positions.delete',
      'shifts.create',
      'shifts.read',
      'shifts.update',
      'shifts.delete',
      'attendance.create',
      'attendance.read',
      'attendance.update',
      'leave_requests.create',
      'leave_requests.read',
      'leave_requests.approve',
      'leave_requests.reject',
      'staff_documents.upload',
      'staff_documents.read',
      'staff_documents.delete',
    ],
  },
  {
    category: 'reports',
    keys: [
      'reports.dashboard.read',
      'reports.daily_summary.read',
      'reports.occupancy.read',
      'reports.arrivals_departures.read',
      'reports.room_status.read',
      'reports.revenue.read',
      'reports.payment_summary.read',
      'reports.department_performance.read',
      'reports.profit_summary.read',
      'reports.housekeeping.read',
      'reports.maintenance.read',
      'reports.outlet_sales.read',
      'reports.inventory.read',
      'reports.procurement.read',
      'reports.hr.read',
    ],
  },
  {
    category: 'approvals',
    keys: [
      'approval_requests.create',
      'approval_requests.read',
      'approval_requests.approve',
      'approval_requests.reject',
      'large_discount.approve',
      'refund.approve',
      'inventory_adjustment.approve',
      'purchase_request.approve',
      'purchase_order.approve',
      'room_out_of_order.approve',
    ],
  },
  {
    category: 'audit_logs',
    keys: ['audit_logs.read', 'audit_logs.export'],
  },
  {
    category: 'notifications',
    keys: [
      'notifications.read',
      'notifications.send',
      'notifications.manage_templates',
    ],
  },
  {
    category: 'files',
    keys: ['files.upload', 'files.read', 'files.delete', 'files.read.own'],
  },
  {
    category: 'guest_portal',
    keys: [
      'guest_portal.booking.create',
      'guest_portal.reservations.read.own',
      'guest_portal.profile.update.own',
      'guest_portal.payments.create.own',
      'guest_portal.invoices.read.own',
      'guest_portal.receipts.read.own',
      'guest_portal.service_requests.create.own',
      'guest_portal.service_requests.read.own',
      'guest_portal.feedback.create.own',
    ],
  },
] as const satisfies readonly DefaultPermissionCategory[];

function formatPermissionName(key: string) {
  return key
    .replace(/[._]/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export const DEFAULT_PERMISSIONS: readonly DefaultPermission[] =
  DEFAULT_PERMISSION_CATEGORIES.flatMap(({ category, keys }) =>
    keys.map((key) => ({
      key,
      name: formatPermissionName(key),
      category,
    })),
  );

export const DEFAULT_PERMISSION_KEYS = DEFAULT_PERMISSIONS.map(
  (permission) => permission.key,
);
